#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" telly
usermod -o -u "$PUID" telly

echo '

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u telly)
User GID:    $(id -g telly)
───────────────────────────────────────
"

chown -R telly:telly /config
chown -R telly:telly /usr/bin/telly 